// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#include "Practica1EDD2018.h"




std::string Practica1EDD2018::devolver(const std::string& id)
{
	

    return "resultado" + id;
}