// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#ifndef PRACTICA1EDD2018_H
#define PRACTICA1EDD2018_H

#include <ngrest/common/Service.h>


//! Dummy description for the service
/*! Some detailed description of the service */
// '*location' comment sets resource path for this service
// *location: practica1edd2018


class Practica1EDD2018: public ngrest::Service
{
public:
 

    // *method: POST
    // *location: /devolver
    std::string devolver(const std::string& id);
};


#endif // PRACTICA1EDD2018_H



