// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#include "Practica1EDD2018.h"


ListaUsuario mlist;
PilaRecurso  mpila;


std::string Practica1EDD2018::newuser(const usuario& User)
{
	 std::string result;
	 result = mlist.insertarLista(User);
	return result;
}


std::list<usuario> Practica1EDD2018::getUsuarios()
{
	std::list<usuario> lista;

	lista =mlist.linealizar();

	return lista;
}


std::string Practica1EDD2018::newrecurso(const recurso& R)
{
	std::string result = "no OK";

	mpila.push(R);

	result = "ok";

	return result;
}